libbgp: libbgp::BgpBadMessage Class Reference
libbgp::BgpBadMessage Class Reference
The BgpBadMessage class.
#include <bgp-bad-message.h>
Public Member Functions
BgpBadMessage (BgpLogHandler *logger, uint8_t type)
Construct a new Bgp Bad Message:: Bgp Bad Message object.
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
ssize_t parse (const uint8_t *from, size_t msg_sz)
Deserialize a BGP message body.
ssize_t write (uint8_t *to, size_t buf_sz) const
Serialize a BGP message body.
def __init__ (self, logger, type)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp::BgpMessage
BgpMessage (BgpLogHandler *logger)
Construct a new Bgp Message object.
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
this
Public Attributes inherited from libbgp::BgpMessage
uint8_t type
Additional Inherited Members
Static Public Attributes inherited from libbgp::BgpMessage
type = _swig_property(_libbgp.BgpMessage_type_get, _libbgp.BgpMessage_type_set)
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
The BgpBadMessage class.
Container class for invalid BGP message.
Definition at line 24 of file bgp-bad-message.h.
Constructor & Destructor Documentation
BgpBadMessage()
libbgp::BgpBadMessage::BgpBadMessage (BgpLogHandler * logger, uint8_t type)
Construct a new Bgp Bad Message:: Bgp Bad Message object.
Parameters
logger Pointer to logger object for error logging.
type Message type.
Definition at line 23 of file bgp-bad-message.cc.
References libbgp::BgpLogHandler::log(), and parse().
Member Function Documentation
doPrint()
ssize_t libbgp::BgpBadMessage::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Implements libbgp.Serializable.
parse()
ssize_t libbgp::BgpBadMessage::parse (const uint8_t * from, size_t msg_sz) virtual
Deserialize a BGP message body.
BgpMessage deserializer only deserialize message body. (i.e. message without BGP marker and message length field) To deserialize a BGP packet, use BgpPacket.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Implements libbgp::BgpMessage.
Referenced by BgpBadMessage().
write()
ssize_t libbgp::BgpBadMessage::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP message body.
BgpMessage serializer only serialize message body. (i.e. message without BGP marker and message length field) To serialize a BGP packet, use BgpPacket.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp::BgpMessage.
The documentation for this class was generated from the following files:
src/bgp-bad-message.h
src/libbgp.py
src/bgp-bad-message.cc