libbgp: libbgp::BgpCapabilityMpBgp Class Reference
libbgp::BgpCapabilityMpBgp Class Reference
The BgpCapabilityMpBgp class.
#include <bgp-capability.h>
Public Member Functions
BgpCapabilityMpBgp (BgpLogHandler *logger)
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
ssize_t parse (const uint8_t *from, size_t msg_sz)
Deserialize a BGP open message capability.
ssize_t write (uint8_t *to, size_t buf_sz) const
Serialize a BGP open message capability.
def __init__ (self, logger)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp::BgpCapability
BgpCapability (BgpLogHandler *logger)
Construct a new Bgp Capability object.
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
uint16_t afi
Address Family Identifier.
uint8_t safi
Subsequent Address Family Identifier.
this
Public Attributes inherited from libbgp::BgpCapability
uint8_t code
Static Public Attributes
afi = _swig_property(_libbgp.BgpCapabilityMpBgp_afi_get, _libbgp.BgpCapabilityMpBgp_afi_set)
safi = _swig_property(_libbgp.BgpCapabilityMpBgp_safi_get, _libbgp.BgpCapabilityMpBgp_safi_set)
Static Public Attributes inherited from libbgp::BgpCapability
code = _swig_property(_libbgp.BgpCapability_code_get, _libbgp.BgpCapability_code_set)
Additional Inherited Members
Protected Member Functions inherited from libbgp::BgpCapability
ssize_t parseHeader (const uint8_t *from, size_t msg_sz)
Parse the capability header (code, length).
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp::BgpCapability
uint8_t length
Length of the attribute. Used only when deserializer.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
The BgpCapabilityMpBgp class.
Definition at line 110 of file bgp-capability.h.
Member Function Documentation
doPrint()
ssize_t libbgp::BgpCapabilityMpBgp::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Implements libbgp.Serializable.
Definition at line 119 of file bgp-capability.cc.
References libbgp.Serializable::_print().
parse()
ssize_t libbgp::BgpCapabilityMpBgp::parse (const uint8_t * from, size_t msg_sz) virtual
Deserialize a BGP open message capability.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Implements libbgp::BgpCapability.
Definition at line 148 of file bgp-capability.cc.
References libbgp::BgpCapability::parseHeader().
write()
ssize_t libbgp::BgpCapabilityMpBgp::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP open message capability.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp::BgpCapability.
Definition at line 176 of file bgp-capability.cc.
References libbgp::BgpLogHandler::log().
The documentation for this class was generated from the following files:
src/bgp-capability.h
src/libbgp.py
src/bgp-capability.cc