libbgp: libbgp::BgpCapability Class Reference
libbgp::BgpCapability Class Reference abstract
The BgpCapability base class.
#include <bgp-capability.h>
Public Member Functions
BgpCapability (BgpLogHandler *logger)
Construct a new Bgp Capability object.
virtual ssize_t parse (const uint8_t *from, size_t msg_sz)=0
Deserialize a BGP open message capability.
virtual ssize_t write (uint8_t *to, size_t buf_sz) const =0
Serialize a BGP open message capability.
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
uint8_t code
Static Public Attributes
code = _swig_property(_libbgp.BgpCapability_code_get, _libbgp.BgpCapability_code_set)
Protected Member Functions
ssize_t parseHeader (const uint8_t *from, size_t msg_sz)
Parse the capability header (code, length).
Protected Member Functions inherited from libbgp.Serializable
virtual ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const =0
Print implementation.
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Protected Attributes
uint8_t length
Length of the attribute. Used only when deserializer.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Additional Inherited Members
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Detailed Description
The BgpCapability base class.
Definition at line 40 of file bgp-capability.h.
Constructor & Destructor Documentation
BgpCapability()
libbgp::BgpCapability::BgpCapability (BgpLogHandler * logger)
Construct a new Bgp Capability object.
Parameters
logger Pointer to logger object for error logging.
Definition at line 25 of file bgp-capability.cc.
References libbgp.Serializable::length().
Member Function Documentation
parse()
virtual ssize_t libbgp::BgpCapability::parse (const uint8_t * from, size_t msg_sz) pure virtual
Deserialize a BGP open message capability.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Implements libbgp.Serializable.
Implemented in libbgp::BgpCapabilityUnknow, libbgp::BgpCapabilityMpBgp, and libbgp::BgpCapability4BytesAsn.
parseHeader()
ssize_t libbgp::BgpCapability::parseHeader (const uint8_t * from, size_t msg_sz) protected
Parse the capability header (code, length).
Parameters
from Pointer to buffer.
msg_sz Max read size.
Returns
ssize_t Bytes read.
Return values
-1 Failed to deserialize header. errbuf may have details. (see bgp-error.h)
>=0 Bytes read.
Definition at line 39 of file bgp-capability.cc.
References libbgp.Serializable::setError().
Referenced by libbgp::BgpCapability4BytesAsn::parse(), libbgp::BgpCapabilityMpBgp::parse(), and libbgp::BgpCapabilityUnknow::parse().
write()
virtual ssize_t libbgp::BgpCapability::write (uint8_t * to, size_t buf_sz) const pure virtual
Serialize a BGP open message capability.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp.Serializable.
Implemented in libbgp::BgpCapabilityUnknow, libbgp::BgpCapabilityMpBgp, and libbgp::BgpCapability4BytesAsn.
Member Data Documentation
length
uint8_t libbgp::BgpCapability::length protected
Length of the attribute. Used only when deserializer.
Length field is only used in deserialization for parseHeader() to pass attribute length to the underlying deserializers. The length field is ignored when serialize (except BgpCapabilityUnknow).
Definition at line 84 of file bgp-capability.h.
The documentation for this class was generated from the following files:
src/bgp-capability.h
src/libbgp.py
src/bgp-capability.cc