libbgp: libbgp::Route6 Class Reference
libbgp::Route6 Class Reference
IPv6 Route/Prefix related utilities.
#include <route6.h>
Public Member Functions
Route6 (const uint8_t prefix[16], uint8_t length)
Construct a new Route6 object.
Route6 (const char *prefix, uint8_t length)
Construct a new Route6 object.
bool includes (const uint8_t address[16]) const
Test if an address is inside this prefix.
bool includes (const char *address) const
Test if an address is inside this prefix.
bool includes (const Route6 &other) const
Test if another prefix is inside this prefix.
bool includes (const uint8_t prefix[16], uint8_t length) const
Test if another prefix is inside this prefix.
bool includes (const char *prefix, uint8_t length) const
Test if another prefix is inside this prefix.
bool operator== (const Route6 &other) const
Test if two routes are equals.
bool operator> (const Route6 &other) const
bool operator< (const Route6 &other) const
bool operator>= (const Route6 &other) const
bool operator<= (const Route6 &other) const
bool operator!= (const Route6 &other) const
bool set (const uint8_t prefix[16], uint8_t length)
Set route.
bool setPrefix (const uint8_t prefix[16])
Set prefix.
bool setLength (uint8_t length)
Set netmask.
void getPrefix (uint8_t prefix[16]) const
Get prefix.
uint8_t getLength () const
Get netmask.
void getMask (uint8_t mask[16]) const
Get netmask.
Static Public Member Functions
static bool Includes (const uint8_t prefix[16], uint8_t length, const uint8_t address[16])
Test if an address is inside a prefix.
static bool Includes (const uint8_t prefix_a[16], uint8_t length_a, const uint8_t prefix_b[16], uint8_t length_b)
Test if a prefix is inside another prefix.
Detailed Description
IPv6 Route/Prefix related utilities.
Definition at line 24 of file route6.h.
Constructor & Destructor Documentation
Route6() [1/2]
libbgp::Route6::Route6 (const uint8_t prefix[16], uint8_t length)
Construct a new Route6 object.
Parameters
prefix Prefix as bytes array.
length Netmask of the prefix in CIDR notation.
Definition at line 189 of file route6.cc.
Route6() [2/2]
libbgp::Route6::Route6 (const char * prefix, uint8_t length)
Construct a new Route6 object.
Parameters
prefix Prefix as IPv6 string.
length Netmask of the prefix in CIDR notation.
Definition at line 200 of file route6.cc.
Member Function Documentation
getLength()
uint8_t libbgp::Route6::getLength () const
Get netmask.
Returns
uint8_t The netmask in CIDR notation.
Definition at line 383 of file route6.cc.
getMask()
void libbgp::Route6::getMask (uint8_t mask[16]) const
Get netmask.
Parameters
mask Bytes array to store the netmask.
Exceptions
bad_route_length Netmask invalid.
Definition at line 393 of file route6.cc.
References libbgp::cidr_to_mask6().
getPrefix()
void libbgp::Route6::getPrefix (uint8_t prefix[16]) const
Get prefix.
Parameters
prefix Bytes array to store the prefix.
Definition at line 374 of file route6.cc.
Includes() [1/2]
bool libbgp::Route6::Includes (const uint8_t prefix[16], uint8_t length, const uint8_t address[16]) static
Test if an address is inside a prefix.
Parameters
prefix The prefix.
length The netmask of the prefix in CIDR notation.
address The address to test against.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 214 of file route6.cc.
References libbgp::mask_ipv6().
Referenced by includes().
Includes() [2/2]
bool libbgp::Route6::Includes (const uint8_t prefix_a[16], uint8_t length_a, const uint8_t prefix_b[16], uint8_t length_b) static
Test if a prefix is inside another prefix.
Parameters
prefix_a The prefix.
length_a The netmask of the prefix in CIDR notation.
prefix_b The orefix to test against.
length_b The netmask of the prefix to test against in CIDR notation.
Returns
true prefix_b is in prefix_a.
false prefix_b is not in prefix_a.
Definition at line 233 of file route6.cc.
References libbgp::mask_ipv6().
includes() [1/5]
bool libbgp::Route6::includes (const uint8_t address[16]) const
Test if an address is inside this prefix.
Parameters
address The address.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 250 of file route6.cc.
References Includes().
Referenced by includes(), and libbgp::BgpRib6::lookup().
includes() [2/5]
bool libbgp::Route6::includes (const char * address) const
Test if an address is inside this prefix.
Parameters
address The address in IPv6 string format.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 261 of file route6.cc.
References includes().
includes() [3/5]
bool libbgp::Route6::includes (const Route6 & other) const
Test if another prefix is inside this prefix.
Parameters
other The other prefix.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 274 of file route6.cc.
References includes().
includes() [4/5]
bool libbgp::Route6::includes (const uint8_t prefix[16], uint8_t length) const
Test if another prefix is inside this prefix.
Parameters
prefix The other prefix.
length Netmask of the other prefix in CIDR notation.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 286 of file route6.cc.
References Includes().
includes() [5/5]
bool libbgp::Route6::includes (const char * prefix, uint8_t length) const
Test if another prefix is inside this prefix.
Parameters
prefix The other prefix in IPv6 string notation.
length Netmask of the other prefix in CIDR notation.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 298 of file route6.cc.
References Includes().
operator==()
bool libbgp::Route6::operator== (const Route6 & other) const
Test if two routes are equals.
Parameters
other The other route object.
Returns
true The routes are equal.
false The routes are different.
Definition at line 311 of file route6.cc.
set()
bool libbgp::Route6::set (const uint8_t prefix[16], uint8_t length)
Set route.
Parameters
prefix Prefix.
length The netmask in CIDR notation.
Returns
true Route set.
false Failed to set route.s
Definition at line 343 of file route6.cc.
setLength()
bool libbgp::Route6::setLength (uint8_t length)
Set netmask.
Parameters
length The netmask in CIDR notation.
Returns
true Netmask set.
false Failed to set netmask.
Definition at line 365 of file route6.cc.
setPrefix()
bool libbgp::Route6::setPrefix (const uint8_t prefix[16])
Set prefix.
Parameters
prefix Prefix to set.
Returns
true Prefix set.
false Failed to set prefix.
Definition at line 354 of file route6.cc.
The documentation for this class was generated from the following files:
src/route6.h
src/route6.cc