libbgp: libbgp::BgpPathAttrib Class Reference
libbgp::BgpPathAttrib Class Reference
The BgpPathAttrib class.
#include <bgp-path-attrib.h>
Public Member Functions
BgpPathAttrib (BgpLogHandler *logger)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
BgpPathAttrib (BgpLogHandler *logger, const uint8_t *value, uint16_t val_len)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
virtual ssize_t parse (const uint8_t *from, size_t msg_sz)
Deserialize a BGP update message path attribute.
virtual ssize_t write (uint8_t *to, size_t buf_sz) const
Serialize a BGP update message path attribute.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
BgpPathAttrib * clone (BgpLogHandler *new_logger) const
Clone the attribute and replace logger.
virtual BgpPathAttrib * clone () const
Clone the attribute.
virtual ~BgpPathAttrib ()
Destroy the Bgp Path Attrib:: Bgp Path Attrib object.
def __init__ (self, args)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def clone (self, args)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Static Public Member Functions
static uint8_t GetTypeFromBuffer (const uint8_t *buffer, size_t buffer_sz)
Public Attributes
bool optional
Attribute flag: Optional.
bool transitive
Attribute flag: Transitive.
bool partial
Attribute flag: partial.
bool extended
Attribute flag: extended.
uint8_t type_code
Attribute type code.
this
Static Public Attributes
optional = _swig_property(_libbgp.BgpPathAttrib_optional_get, _libbgp.BgpPathAttrib_optional_set)
transitive = _swig_property(_libbgp.BgpPathAttrib_transitive_get, _libbgp.BgpPathAttrib_transitive_set)
partial = _swig_property(_libbgp.BgpPathAttrib_partial_get, _libbgp.BgpPathAttrib_partial_set)
extended = _swig_property(_libbgp.BgpPathAttrib_extended_get, _libbgp.BgpPathAttrib_extended_set)
type_code = _swig_property(_libbgp.BgpPathAttrib_type_code_get, _libbgp.BgpPathAttrib_type_code_set)
GetTypeFromBuffer = staticmethod(_libbgp.BgpPathAttrib_GetTypeFromBuffer)
Get type of attribute from buffer.
Protected Member Functions
ssize_t parseHeader (const uint8_t *buffer, size_t length)
Utility function to parse attribute header. (Flag, type, length)
ssize_t printFlags (size_t indent, uint8_t **to, size_t *buf_sz) const
Utility function to print flags for attribute.
ssize_t writeHeader (uint8_t *buffer, size_t buffer_sz) const
Write attribute header to buffer. (Flag, Type)
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Protected Attributes
uint16_t value_len
Attribute length. Length field is only used in deserialization for parseHeader() to pass length field in header to the underlying deserializers. The length field is ignored when serialize.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Additional Inherited Members
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Detailed Description
The BgpPathAttrib class.
Definition at line 47 of file bgp-path-attrib.h.
Constructor & Destructor Documentation
BgpPathAttrib() [1/2]
libbgp::BgpPathAttrib::BgpPathAttrib (BgpLogHandler * logger)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
Parameters
logger Pointer to logger object for error logging.
Definition at line 39 of file bgp-path-attrib.cc.
References extended, optional, partial, and transitive.
Referenced by libbgp::BgpPathAttribCommunity::length().
BgpPathAttrib() [2/2]
libbgp::BgpPathAttrib::BgpPathAttrib (BgpLogHandler * logger, const uint8_t * value, uint16_t val_len)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
Parameters
logger Pointer to logger object for error logging.
value Pointer to value buffer of unknow type attribute.
val_len Length of the value buffer.
Definition at line 51 of file bgp-path-attrib.cc.
References libbgp::BgpLogHandler::log(), and value_len.
Member Function Documentation
clone() [1/2]
BgpPathAttrib * libbgp::BgpPathAttrib::clone (BgpLogHandler * new_logger) const
Clone the attribute and replace logger.
Parameters
new_logger New logger to use.
Returns
BgpPathAttrib* Pointer to the cloned attribute.
Exceptions
has_error There's error in the attribute and the attribute can not be clone.
Definition at line 69 of file bgp-path-attrib.cc.
References clone().
Referenced by libbgp::BgpUpdateMessage::addAttrib().
clone() [2/2]
BgpPathAttrib * libbgp::BgpPathAttrib::clone () const virtual
Clone the attribute.
Returns
BgpPathAttrib* Pointer to the cloned attribute.
Exceptions
has_error There's error in the attribute and the attribute can not be clone.
Reimplemented in libbgp::BgpPathAttribMpUnreachNlriUnknow, libbgp::BgpPathAttribMpUnreachNlriIpv6, libbgp::BgpPathAttribMpReachNlriUnknow, libbgp::BgpPathAttribMpReachNlriIpv6, libbgp::BgpPathAttribCommunity, libbgp::BgpPathAttribAs4Aggregator, libbgp::BgpPathAttribAs4Path, libbgp::BgpPathAttribAggregator, libbgp::BgpPathAttribAtomicAggregate, libbgp::BgpPathAttribLocalPref, libbgp::BgpPathAttribMed, libbgp::BgpPathAttribNexthop, libbgp::BgpPathAttribAsPath, and libbgp::BgpPathAttribOrigin.
Definition at line 75 of file bgp-path-attrib.cc.
References libbgp.Serializable::hasError(), and libbgp::BgpLogHandler::log().
Referenced by clone().
doPrint()
ssize_t libbgp::BgpPathAttrib::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Implements libbgp.Serializable.
Reimplemented in libbgp::BgpPathAttribMpUnreachNlriUnknow, libbgp::BgpPathAttribMpUnreachNlriIpv6, libbgp::BgpPathAttribMpReachNlriUnknow, libbgp::BgpPathAttribMpReachNlriIpv6, libbgp::BgpPathAttribCommunity, libbgp::BgpPathAttribAs4Aggregator, libbgp::BgpPathAttribAs4Path, libbgp::BgpPathAttribAggregator, libbgp::BgpPathAttribAtomicAggregate, libbgp::BgpPathAttribLocalPref, libbgp::BgpPathAttribMed, libbgp::BgpPathAttribNexthop, libbgp::BgpPathAttribAsPath, and libbgp::BgpPathAttribOrigin.
Definition at line 116 of file bgp-path-attrib.cc.
References libbgp.Serializable::_print(), printFlags(), and type_code.
length()
ssize_t libbgp::BgpPathAttrib::length () const virtual
Get size in bytes required to serialize the object.
Returns
ssize_t Size in btyes.
Return values
-1 Failed to get size.
>=0 Size in btyes.
Reimplemented from libbgp.Serializable.
Reimplemented in libbgp::BgpPathAttribMpUnreachNlriUnknow, libbgp::BgpPathAttribMpUnreachNlriIpv6, libbgp::BgpPathAttribMpReachNlriUnknow, libbgp::BgpPathAttribMpReachNlriIpv6, libbgp::BgpPathAttribCommunity, libbgp::BgpPathAttribAs4Aggregator, libbgp::BgpPathAttribAs4Path, libbgp::BgpPathAttribAggregator, libbgp::BgpPathAttribAtomicAggregate, libbgp::BgpPathAttribLocalPref, libbgp::BgpPathAttribMed, libbgp::BgpPathAttribNexthop, libbgp::BgpPathAttribAsPath, and libbgp::BgpPathAttribOrigin.
Definition at line 164 of file bgp-path-attrib.cc.
References extended, and value_len.
parse()
ssize_t libbgp::BgpPathAttrib::parse (const uint8_t * from, size_t msg_sz) virtual
Deserialize a BGP update message path attribute.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Implements libbgp.Serializable.
Reimplemented in libbgp::BgpPathAttribMpUnreachNlriUnknow, libbgp::BgpPathAttribMpUnreachNlriIpv6, libbgp::BgpPathAttribMpReachNlriUnknow, libbgp::BgpPathAttribMpReachNlriIpv6, libbgp::BgpPathAttribCommunity, libbgp::BgpPathAttribAs4Aggregator, libbgp::BgpPathAttribAs4Path, libbgp::BgpPathAttribAggregator, libbgp::BgpPathAttribAtomicAggregate, libbgp::BgpPathAttribLocalPref, libbgp::BgpPathAttribMed, libbgp::BgpPathAttribNexthop, libbgp::BgpPathAttribAsPath, and libbgp::BgpPathAttribOrigin.
Definition at line 129 of file bgp-path-attrib.cc.
References optional, parseHeader(), libbgp.Serializable::setError(), and transitive.
parseHeader()
ssize_t libbgp::BgpPathAttrib::parseHeader (const uint8_t * from, size_t buffer_sz) protected
Utility function to parse attribute header. (Flag, type, length)
Parameters
from Pointer to buffer.
buffer_sz Size of buffer.
Returns
ssize_t Bytes read.
Return values
-1 Failed to parse header. error may be written to stderr with log handler.
>=0 Bytes read.
Definition at line 200 of file bgp-path-attrib.cc.
References libbgp.Serializable::setError().
Referenced by libbgp::BgpPathAttribCommunity::length(), parse(), libbgp::BgpPathAttribOrigin::parse(), libbgp::BgpPathAttribAsPath::parse(), libbgp::BgpPathAttribNexthop::parse(), libbgp::BgpPathAttribMed::parse(), libbgp::BgpPathAttribLocalPref::parse(), libbgp::BgpPathAttribAtomicAggregate::parse(), libbgp::BgpPathAttribAggregator::parse(), libbgp::BgpPathAttribAs4Path::parse(), libbgp::BgpPathAttribAs4Aggregator::parse(), libbgp::BgpPathAttribCommunity::parse(), libbgp::BgpPathAttribMpReachNlriIpv6::parse(), libbgp::BgpPathAttribMpReachNlriUnknow::parse(), libbgp::BgpPathAttribMpUnreachNlriIpv6::parse(), and libbgp::BgpPathAttribMpUnreachNlriUnknow::parse().
printFlags()
ssize_t libbgp::BgpPathAttrib::printFlags (size_t indent, uint8_t ** to, size_t * buf_sz) const protected
Utility function to print flags for attribute.
Parameters
indent Indentation level.
to Pointer to buffer pointer.
buf_sz Pointer to avaliable buffer counter.
Returns
ssize_t Bytes written.
Definition at line 96 of file bgp-path-attrib.cc.
References libbgp.Serializable::_print(), extended, optional, partial, and transitive.
Referenced by doPrint(), libbgp::BgpPathAttribOrigin::doPrint(), libbgp::BgpPathAttribAsPath::doPrint(), libbgp::BgpPathAttribNexthop::doPrint(), libbgp::BgpPathAttribMed::doPrint(), libbgp::BgpPathAttribLocalPref::doPrint(), libbgp::BgpPathAttribAtomicAggregate::doPrint(), libbgp::BgpPathAttribAggregator::doPrint(), libbgp::BgpPathAttribAs4Path::doPrint(), libbgp::BgpPathAttribAs4Aggregator::doPrint(), libbgp::BgpPathAttribCommunity::doPrint(), libbgp::BgpPathAttribMpReachNlriIpv6::doPrint(), libbgp::BgpPathAttribMpReachNlriUnknow::doPrint(), libbgp::BgpPathAttribMpUnreachNlriIpv6::doPrint(), and libbgp::BgpPathAttribMpUnreachNlriUnknow::doPrint().
write()
ssize_t libbgp::BgpPathAttrib::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP update message path attribute.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp.Serializable.
Reimplemented in libbgp::BgpPathAttribMpUnreachNlriUnknow, libbgp::BgpPathAttribMpUnreachNlriIpv6, libbgp::BgpPathAttribMpReachNlriUnknow, libbgp::BgpPathAttribMpReachNlriIpv6, libbgp::BgpPathAttribCommunity, libbgp::BgpPathAttribAs4Aggregator, libbgp::BgpPathAttribAs4Path, libbgp::BgpPathAttribAggregator, libbgp::BgpPathAttribAtomicAggregate, libbgp::BgpPathAttribLocalPref, libbgp::BgpPathAttribMed, libbgp::BgpPathAttribNexthop, libbgp::BgpPathAttribAsPath, and libbgp::BgpPathAttribOrigin.
Definition at line 168 of file bgp-path-attrib.cc.
References libbgp::BgpLogHandler::log(), and value_len.
writeHeader()
ssize_t libbgp::BgpPathAttrib::writeHeader (uint8_t * to, size_t buffer_sz) const protected
Write attribute header to buffer. (Flag, Type)
Write attribute header to buffer. Notice that only attribute flags and type will be written to buffer. You need to write attribute length yourself.
Parameters
to Destnation buiffer.
buffer_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Failed to write buffer. error may be written to stderr with log handler.
>=0 Bytes written.
Definition at line 251 of file bgp-path-attrib.cc.
References extended, and libbgp::BgpLogHandler::log().
Referenced by libbgp::BgpPathAttribMpReachNlriIpv6::write().
Member Data Documentation
GetTypeFromBuffer
uint8_t libbgp.BgpPathAttrib.GetTypeFromBuffer = staticmethod(_libbgp.BgpPathAttrib_GetTypeFromBuffer) static
Get type of attribute from buffer.
Parameters
from Pointer to buffer.
buffer_sz Size of buffre.
Returns
int8_t Attribute type.
Return values
0 Failed to get attribute type.
>0 Attribute type.
Definition at line 1572 of file libbgp.py.
The documentation for this class was generated from the following files:
src/bgp-path-attrib.h
src/libbgp.py
src/bgp-path-attrib.cc