libbgp: libbgp::BgpPathAttribAsPath Class Reference
libbgp::BgpPathAttribAsPath Class Reference
AS Path attribute.
#include <bgp-path-attrib.h>
Public Member Functions
BgpPathAttribAsPath (BgpLogHandler *logger, bool is_4b)
Construct a new Bgp Path Attrib As Path:: Bgp Path Attrib As Path object.
BgpPathAttrib * clone () const
Clone the attribute.
bool prepend (uint32_t asn)
Prepend an ASN into AS path.
ssize_t parse (const uint8_t *buffer, size_t length)
Deserialize a BGP update message path attribute.
ssize_t write (uint8_t *buffer, size_t buffer_sz) const
Serialize a BGP update message path attribute.
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
ssize_t length () const
Get size in bytes required to serialize the object.
def __init__ (self, logger, is_4b)
def clone (self)
def prepend (self, asn)
def parse (self, buffer, length)
def write (self, buffer, buffer_sz)
def doPrint (self, indent, to, buf_sz)
def length (self)
Public Member Functions inherited from libbgp::BgpPathAttrib
BgpPathAttrib (BgpLogHandler *logger)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
BgpPathAttrib (BgpLogHandler *logger, const uint8_t *value, uint16_t val_len)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
BgpPathAttrib * clone (BgpLogHandler *new_logger) const
Clone the attribute and replace logger.
virtual ~BgpPathAttrib ()
Destroy the Bgp Path Attrib:: Bgp Path Attrib object.
def __init__ (self, args)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def clone (self, args)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
std::vector< BgpAsPathSegment > as_paths
The AS Path segments.
bool is_4b
Is ASNs in the attribute four octets?
this
Public Attributes inherited from libbgp::BgpPathAttrib
bool optional
Attribute flag: Optional.
bool transitive
Attribute flag: Transitive.
bool partial
Attribute flag: partial.
bool extended
Attribute flag: extended.
uint8_t type_code
Attribute type code.
this
Static Public Attributes
as_paths = _swig_property(_libbgp.BgpPathAttribAsPath_as_paths_get, _libbgp.BgpPathAttribAsPath_as_paths_set)
is_4b = _swig_property(_libbgp.BgpPathAttribAsPath_is_4b_get, _libbgp.BgpPathAttribAsPath_is_4b_set)
Static Public Attributes inherited from libbgp::BgpPathAttrib
optional = _swig_property(_libbgp.BgpPathAttrib_optional_get, _libbgp.BgpPathAttrib_optional_set)
transitive = _swig_property(_libbgp.BgpPathAttrib_transitive_get, _libbgp.BgpPathAttrib_transitive_set)
partial = _swig_property(_libbgp.BgpPathAttrib_partial_get, _libbgp.BgpPathAttrib_partial_set)
extended = _swig_property(_libbgp.BgpPathAttrib_extended_get, _libbgp.BgpPathAttrib_extended_set)
type_code = _swig_property(_libbgp.BgpPathAttrib_type_code_get, _libbgp.BgpPathAttrib_type_code_set)
GetTypeFromBuffer = staticmethod(_libbgp.BgpPathAttrib_GetTypeFromBuffer)
Get type of attribute from buffer.
Additional Inherited Members
Static Public Member Functions inherited from libbgp::BgpPathAttrib
static uint8_t GetTypeFromBuffer (const uint8_t *buffer, size_t buffer_sz)
Protected Member Functions inherited from libbgp::BgpPathAttrib
ssize_t parseHeader (const uint8_t *buffer, size_t length)
Utility function to parse attribute header. (Flag, type, length)
ssize_t printFlags (size_t indent, uint8_t **to, size_t *buf_sz) const
Utility function to print flags for attribute.
ssize_t writeHeader (uint8_t *buffer, size_t buffer_sz) const
Write attribute header to buffer. (Flag, Type)
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp::BgpPathAttrib
uint16_t value_len
Attribute length. Length field is only used in deserialization for parseHeader() to pass length field in header to the underlying deserializers. The length field is ignored when serialize.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
AS Path attribute.
Definition at line 229 of file bgp-path-attrib.h.
Constructor & Destructor Documentation
BgpPathAttribAsPath()
libbgp::BgpPathAttribAsPath::BgpPathAttribAsPath (BgpLogHandler * logger, bool is_4b)
Construct a new Bgp Path Attrib As Path:: Bgp Path Attrib As Path object.
Parameters
logger Pointer to logger object for error logging.
is_4b Enable four octets ASN support.
Definition at line 367 of file bgp-path-attrib.cc.
References is_4b, libbgp::BgpPathAttrib::transitive, and libbgp::BgpPathAttrib::type_code.
Member Function Documentation
clone()
BgpPathAttrib * libbgp::BgpPathAttribAsPath::clone () const virtual
Clone the attribute.
Returns
BgpPathAttrib* Pointer to the cloned attribute.
Exceptions
has_error There's error in the attribute and the attribute can not be clone.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 408 of file bgp-path-attrib.cc.
References libbgp.Serializable::hasError(), and libbgp::BgpLogHandler::log().
doPrint()
ssize_t libbgp::BgpPathAttribAsPath::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 416 of file bgp-path-attrib.cc.
References libbgp.Serializable::_print(), as_paths, is_4b, and libbgp::BgpPathAttrib::printFlags().
length()
ssize_t libbgp::BgpPathAttribAsPath::length () const virtual
Get size in bytes required to serialize the object.
Returns
ssize_t Size in btyes.
Return values
-1 Failed to get size.
>=0 Size in btyes.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 510 of file bgp-path-attrib.cc.
References as_paths, and is_4b.
parse()
ssize_t libbgp::BgpPathAttribAsPath::parse (const uint8_t * from, size_t msg_sz) virtual
Deserialize a BGP update message path attribute.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 448 of file bgp-path-attrib.cc.
References libbgp::BgpPathAttrib::parseHeader(), and libbgp::BgpPathAttrib::type_code.
prepend()
bool libbgp::BgpPathAttribAsPath::prepend (uint32_t asn)
Prepend an ASN into AS path.
This method will prepend an ASN to AS_SEQUENCE segment if the segment is the first in path. A new AS_SEQUENCE will be create and append to AS_PATH otherwise. A new AS_SEQUENCE will also be create if the current one is full.
Parameters
asn The ASN to append.
Returns
true ASN prepended.
false Failed to append ASN. error may be written to stderr with log handler.
Definition at line 543 of file bgp-path-attrib.cc.
References as_paths, and libbgp::BgpAsPathSegment::type.
write()
ssize_t libbgp::BgpPathAttribAsPath::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP update message path attribute.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 573 of file bgp-path-attrib.cc.
References libbgp::BgpLogHandler::log().
The documentation for this class was generated from the following files:
src/bgp-path-attrib.h
src/libbgp.py
src/bgp-path-attrib.cc