libbgp: libbgp::BgpOpenMessage Class Reference
libbgp::BgpOpenMessage Class Reference
The BgpOpenMessage class.
#include <bgp-open-message.h>
Public Member Functions
BgpOpenMessage (BgpLogHandler *logger, bool use_4b_asn)
Construct a new Bgp Open Message:: Bgp Open Message object.
BgpOpenMessage (BgpLogHandler *logger, bool use_4b_asn, uint16_t my_asn, uint16_t hold_time, uint32_t bgp_id)
Construct a new Bgp Open Message:: Bgp Open Message object.
BgpOpenMessage (BgpLogHandler *logger, bool use_4b_asn, uint16_t my_asn, uint16_t hold_time, const char *bgp_id)
Construct a new Bgp Open Message:: Bgp Open Message object.
bool setAsn (uint32_t my_asn)
Set ASN.
uint32_t getAsn () const
Get ASN.
bool hasCapability (uint8_t code) const
Check if open message has a capability.
bool addCapability (std::shared_ptr< BgpCapability > capability)
Add a capability.
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
ssize_t parse (const uint8_t *from, size_t msg_sz)
Parse a BGP open message body.
ssize_t write (uint8_t *to, size_t buf_sz) const
Serialize a BGP message body.
const std::vector< std::shared_ptr< BgpCapability > > & getCapabilities () const
Get capabilities list.
def __init__ (self, args)
def setAsn (self, my_asn)
def getAsn (self)
def hasCapability (self, code)
def addCapability (self, capability)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def getCapabilities (self)
Public Member Functions inherited from libbgp::BgpMessage
BgpMessage (BgpLogHandler *logger)
Construct a new Bgp Message object.
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
uint8_t version
uint16_t my_asn
uint16_t hold_time
uint32_t bgp_id
this
Public Attributes inherited from libbgp::BgpMessage
uint8_t type
Static Public Attributes
version = _swig_property(_libbgp.BgpOpenMessage_version_get, _libbgp.BgpOpenMessage_version_set)
my_asn = _swig_property(_libbgp.BgpOpenMessage_my_asn_get, _libbgp.BgpOpenMessage_my_asn_set)
hold_time = _swig_property(_libbgp.BgpOpenMessage_hold_time_get, _libbgp.BgpOpenMessage_hold_time_set)
bgp_id = _swig_property(_libbgp.BgpOpenMessage_bgp_id_get, _libbgp.BgpOpenMessage_bgp_id_set)
Static Public Attributes inherited from libbgp::BgpMessage
type = _swig_property(_libbgp.BgpMessage_type_get, _libbgp.BgpMessage_type_set)
Additional Inherited Members
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
The BgpOpenMessage class.
This is deserializer/serializer for BGP open message body. If you want to deserializer/serializer a full BGP message. Take a look at BgpPacket class.
Examples:
deserialize-and-serialize.cc.
Definition at line 27 of file bgp-open-message.h.
Constructor & Destructor Documentation
BgpOpenMessage() [1/3]
libbgp::BgpOpenMessage::BgpOpenMessage (BgpLogHandler * logger, bool use_4b_asn)
Construct a new Bgp Open Message:: Bgp Open Message object.
Parameters
logger Pointer to logger object for error logging.
use_4b_asn Enable four octets ASN support.
Definition at line 25 of file bgp-open-message.cc.
BgpOpenMessage() [2/3]
libbgp::BgpOpenMessage::BgpOpenMessage (BgpLogHandler * logger, bool use_4b_asn, uint16_t my_asn, uint16_t hold_time, uint32_t bgp_id)
Construct a new Bgp Open Message:: Bgp Open Message object.
Parameters
use_4b_asn Enable four octets ASN support.
my_asn Local ASN (2 octets). If you want to set a four octets ASN, make sure use_4b_asn is true and use BgpOpenMessage::setAsn(uint32_t my_asn)
hold_time Hold timer.
bgp_id Local BGP ID in network byte order
Definition at line 43 of file bgp-open-message.cc.
References setAsn().
BgpOpenMessage() [3/3]
libbgp::BgpOpenMessage::BgpOpenMessage (BgpLogHandler * logger, bool use_4b_asn, uint16_t my_asn, uint16_t hold_time, const char * bgp_id)
Construct a new Bgp Open Message:: Bgp Open Message object.
Parameters
use_4b_asn Enable four octets ASN support.
my_asn Local ASN (2 octets). If you want to set a four octets ASN, make sure use_4b_asn is true and use BgpOpenMessage::setAsn(uint32_t my_asn)
hold_time Hold timer.
bgp_id Local BGP ID in dotted string notation
Definition at line 61 of file bgp-open-message.cc.
References setAsn().
Member Function Documentation
addCapability()
bool libbgp::BgpOpenMessage::addCapability (std::shared_ptr< BgpCapability > capability)
Add a capability.
Parameters
capability The capability.
Returns
true Capability added.
false Failed to add capability.
Definition at line 371 of file bgp-open-message.cc.
doPrint()
ssize_t libbgp::BgpOpenMessage::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Implements libbgp.Serializable.
Definition at line 258 of file bgp-open-message.cc.
References libbgp.Serializable::_print().
getAsn()
uint32_t libbgp::BgpOpenMessage::getAsn () const
Get ASN.
Get ASN of the open message. Will check Capabilities for four octets ASN if four octets ASN support is enabled.
Returns
uint32_t ASN
Definition at line 296 of file bgp-open-message.cc.
getCapabilities()
const std::vector< std::shared_ptr< BgpCapability > > & libbgp::BgpOpenMessage::getCapabilities () const
Get capabilities list.
Returns
const std::vector<std::shared_ptr<BgpCapability>>& Capabilities.
Definition at line 360 of file bgp-open-message.cc.
hasCapability()
bool libbgp::BgpOpenMessage::hasCapability (uint8_t code) const
Check if open message has a capability.
Parameters
code Capability code
Returns
true open message has capability
false open message does not have capability.
Definition at line 347 of file bgp-open-message.cc.
parse()
ssize_t libbgp::BgpOpenMessage::parse (const uint8_t * from, size_t msg_sz) virtual
Parse a BGP open message body.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Parse error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal parser error.
Implements libbgp::BgpMessage.
Definition at line 79 of file bgp-open-message.cc.
References libbgp.Serializable::setError().
setAsn()
bool libbgp::BgpOpenMessage::setAsn (uint32_t my_asn)
Set ASN.
Set ASN of the open message. Will update/create four octets ASN capability if four octets ASN support is enabled.
Parameters
my_asn ASN
Returns
true ASN set
false Failed to set ASN
Examples:
deserialize-and-serialize.cc.
Definition at line 319 of file bgp-open-message.cc.
Referenced by BgpOpenMessage().
write()
ssize_t libbgp::BgpOpenMessage::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP message body.
BgpMessage serializer only serialize message body. (i.e. message without BGP marker and message length field) To serialize a BGP packet, use BgpPacket.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp::BgpMessage.
Definition at line 205 of file bgp-open-message.cc.
References libbgp::BgpLogHandler::log().
The documentation for this class was generated from the following files:
src/bgp-open-message.h
src/libbgp.py
src/bgp-open-message.cc