libbgp: libbgp::BgpRib Class Reference
libbgp::BgpRib Class Reference
The BgpRib (BGP Routing Information Base) class.
#include <bgp-rib.h>
Public Member Functions
BgpRib (BgpLogHandler *logger)
Construct a new BgpRib object with logging.
const BgpRibEntry * insert (BgpLogHandler *logger, const Route &route, uint32_t nexthop)
Insert a local route into RIB.
bool insert (uint32_t src_router_id, const Route &route, const std::vector< std::shared_ptr< BgpPathAttrib >> &attrib)
Insert a new entry into RIB.
ssize_t insert (uint32_t src_router_id, const std::vector< Route > &routes, const std::vector< std::shared_ptr< BgpPathAttrib >> &attrib)
Insert new entries into RIB.
bool withdraw (uint32_t src_router_id, const Route &route)
Withdraw a route from RIB.
ssize_t withdraw (uint32_t src_router_id, const std::vector< Route > &routes)
Withdraw routes from RIB.
std::vector< Route > discard (uint32_t src_router_id)
Drop all routes from RIB that originated from a BGP speaker.
const BgpRibEntry * lookup (uint32_t dest) const
Lookup a destination in RIB.
const BgpRibEntry * lookup (uint32_t src_router_id, uint32_t dest) const
Scoped RIB lookup.
const std::vector< BgpRibEntry > & get () const
Get the RIB.
Detailed Description
The BgpRib (BGP Routing Information Base) class.
Examples:
route-event-bus.cc, and route-server.cc.
Definition at line 67 of file bgp-rib.h.
Constructor & Destructor Documentation
BgpRib()
libbgp::BgpRib::BgpRib (BgpLogHandler * logger)
Construct a new BgpRib object with logging.
Parameters
logger Log handler to use.
Definition at line 69 of file bgp-rib.cc.
References libbgp::BgpRibEntry::update_id.
Member Function Documentation
discard()
std::vector< Route > libbgp::BgpRib::discard (uint32_t src_router_id)
Drop all routes from RIB that originated from a BGP speaker.
Parameters
src_router_id src_router_id Originating BGP speaker's ID in network bytes order.
Returns
std::vector<Route> Dropped routes.
Definition at line 250 of file bgp-rib.cc.
get()
const std::vector< BgpRibEntry > & libbgp::BgpRib::get () const
Get the RIB.
Returns
const std::vector<BgpRibEntry>& The RIB.
Definition at line 340 of file bgp-rib.cc.
insert() [1/3]
const BgpRibEntry * libbgp::BgpRib::insert (BgpLogHandler * logger, const Route & route, uint32_t nexthop)
Insert a local route into RIB.
Local routes are routes inserted to the RIB by user. The scope (src_router_id) of local routes are 0. This method will create necessary path attribues before inserting entry to RIB (AS_PATH, ORIGIN, NEXT_HOP).
The logger pointer passed in is for attribues. (so if a attribute failed to deserialize, it will print to the provided logger).
To remove an entry inserted with this method, use 0 as src_router_id.
Parameters
logger Pointer to logger for the created path attributes to use.
route Route.
nexthop Nexthop for the route.
Return values
NULL failed to insert.
!=NULL Inserted route.
Examples:
route-event-bus.cc, and route-filter.cc.
Definition at line 92 of file bgp-rib.cc.
References libbgp::BgpRibEntry::attribs, and libbgp::BgpPathAttribNexthop::next_hop.
insert() [2/3]
bool libbgp::BgpRib::insert (uint32_t src_router_id, const Route & route, const std::vector< std::shared_ptr< BgpPathAttrib >> & attrib)
Insert a new entry into RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
route Route.
attrib Path attribute.
Returns
true Route inserted/replaced.
false Route already exist and the existing one has lower metric.
Definition at line 141 of file bgp-rib.cc.
References libbgp::BgpRibEntry::getMetric(), and libbgp::BgpRibEntry::update_id.
insert() [3/3]
ssize_t libbgp::BgpRib::insert (uint32_t src_router_id, const std::vector< Route > & routes, const std::vector< std::shared_ptr< BgpPathAttrib >> & attrib)
Insert new entries into RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
routes List of routes.
attrib Path attribute.
Returns
ssize_t Number of routes inserted.
Return values
-1 Failed to insert routes.
>=0 Number of routes inserted.
Definition at line 189 of file bgp-rib.cc.
References libbgp::BgpRibEntry::update_id.
lookup() [1/2]
const BgpRibEntry * libbgp::BgpRib::lookup (uint32_t dest) const
Lookup a destination in RIB.
Parameters
dest The destination address in network byte order.
Returns
const BgpRibEntry* Matching entry.
Return values
NULL no match found.
BgpRibEntry* Matching entry.
Definition at line 298 of file bgp-rib.cc.
References libbgp::Route::includes(), and libbgp::BgpRibEntry::route.
lookup() [2/2]
const BgpRibEntry * libbgp::BgpRib::lookup (uint32_t src_router_id, uint32_t dest) const
Scoped RIB lookup.
Simular to lookup with only one argument but only lookup in routes from the given BGP speaker.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
dest The destination address in network byte order.
Returns
const BgpRibEntry* Matching entry.
Return values
NULL no match found.
BgpRibEntry* Matching entry.
Definition at line 322 of file bgp-rib.cc.
References libbgp::Route::includes(), and libbgp::BgpRibEntry::route.
withdraw() [1/2]
bool libbgp::BgpRib::withdraw (uint32_t src_router_id, const Route & route)
Withdraw a route from RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
route Route.
Returns
true Route dropped.
false Route not dropped. Likely becuase such route does not exist.
Examples:
route-event-bus.cc.
Definition at line 208 of file bgp-rib.cc.
withdraw() [2/2]
ssize_t libbgp::BgpRib::withdraw (uint32_t src_router_id, const std::vector< Route > & routes)
Withdraw routes from RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
routes Routes.
Returns
ssize_t Number of routes dropped.
Return values
-1 Failed to drop routes.
>=0 Number of routes dropped.
Definition at line 236 of file bgp-rib.cc.
The documentation for this class was generated from the following files:
src/bgp-rib.h
src/bgp-rib.cc