libbgp: libbgp::BgpMessage Class Reference
libbgp::BgpMessage Class Reference abstract
The BgpMessage base class.
#include <bgp-message.h>
Public Member Functions
BgpMessage (BgpLogHandler *logger)
Construct a new Bgp Message object.
virtual ssize_t parse (const uint8_t *from, size_t msg_sz)=0
Deserialize a BGP message body.
virtual ssize_t write (uint8_t *to, size_t buf_sz) const =0
Serialize a BGP message body.
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
virtual ssize_t length () const
Get size in bytes required to serialize the object.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
uint8_t type
Static Public Attributes
type = _swig_property(_libbgp.BgpMessage_type_get, _libbgp.BgpMessage_type_set)
Additional Inherited Members
Protected Member Functions inherited from libbgp.Serializable
virtual ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const =0
Print implementation.
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
The BgpMessage base class.
Examples:
deserialize-and-serialize.cc.
Definition at line 35 of file bgp-message.h.
Constructor & Destructor Documentation
BgpMessage()
libbgp::BgpMessage::BgpMessage (BgpLogHandler * logger) inline
Construct a new Bgp Message object.
Parameters
logger Pointer to logger object for error logging.
Definition at line 42 of file bgp-message.h.
References parse(), and write().
Member Function Documentation
parse()
virtual ssize_t libbgp::BgpMessage::parse (const uint8_t * from, size_t msg_sz) pure virtual
Deserialize a BGP message body.
BgpMessage deserializer only deserialize message body. (i.e. message without BGP marker and message length field) To deserialize a BGP packet, use BgpPacket.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Implements libbgp.Serializable.
Implemented in libbgp::BgpUpdateMessage, libbgp::BgpNotificationMessage, libbgp::BgpOpenMessage, libbgp::BgpKeepaliveMessage, and libbgp::BgpBadMessage.
Referenced by BgpMessage().
write()
virtual ssize_t libbgp::BgpMessage::write (uint8_t * to, size_t buf_sz) const pure virtual
Serialize a BGP message body.
BgpMessage serializer only serialize message body. (i.e. message without BGP marker and message length field) To serialize a BGP packet, use BgpPacket.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Implements libbgp.Serializable.
Implemented in libbgp::BgpUpdateMessage, libbgp::BgpNotificationMessage, libbgp::BgpOpenMessage, libbgp::BgpKeepaliveMessage, and libbgp::BgpBadMessage.
Referenced by BgpMessage().
The documentation for this class was generated from the following files:
src/bgp-message.h
src/libbgp.py