libbgp: libbgp::BgpRib4 Class Reference
libbgp::BgpRib4 Class Reference
The BgpRib4 (IPv4 BGP Routing Information Base) class.
#include <bgp-rib4.h>
Public Member Functions
BgpRib4 (BgpLogHandler *logger)
Construct a new BgpRib4 object with logging.
const BgpRib4Entry * insert (BgpLogHandler *logger, const Prefix4 &route, uint32_t nexthop, int32_t weight=0)
Insert a local route into RIB.
const BgpRib4Entry * insert (BgpLogHandler *logger, const Prefix4 &route, uint32_t nexthop, RouteEventBus *rev_bus, int32_t weight=0)
Insert a local route into RIB.
const std::vector< BgpRib4Entry > insert (BgpLogHandler *logger, const std::vector< Prefix4 > &routes, uint32_t nexthop, int32_t weight=0)
Insert local routes into RIB.
const std::vector< BgpRib4Entry > insert (BgpLogHandler *logger, const std::vector< Prefix4 > &routes, uint32_t nexthop, RouteEventBus *rev_bus, int32_t weight=0)
Insert local routes into RIB.
bool insert (uint32_t src_router_id, const Prefix4 &route, const std::vector< std::shared_ptr< BgpPathAttrib >> &attrib, int32_t weight, uint32_t ibgp_asn)
Insert a new entry into RIB.
ssize_t insert (uint32_t src_router_id, const std::vector< Prefix4 > &routes, const std::vector< std::shared_ptr< BgpPathAttrib >> &attrib, int32_t weight, uint32_t ibgp_asn)
Insert new entries into RIB.
bool withdraw (uint32_t src_router_id, const Prefix4 &route)
Withdraw a route from RIB.
bool withdraw (uint32_t src_router_id, const Prefix4 &route, RouteEventBus *rev_bus)
Withdrawn a route from RIB and send event to event bus.
ssize_t withdraw (uint32_t src_router_id, const std::vector< Prefix4 > &routes)
Withdraw routes from RIB.
ssize_t withdraw (uint32_t src_router_id, const std::vector< Prefix4 > &routes, RouteEventBus *rev_bus)
Withdraw routes from RIB and send event to event bus.
std::vector< Prefix4 > discard (uint32_t src_router_id)
Drop all routes from RIB that originated from a BGP speaker.
const BgpRib4Entry * lookup (uint32_t dest) const
Lookup a destination in RIB.
const BgpRib4Entry * lookup (uint32_t src_router_id, uint32_t dest) const
Scoped RIB lookup.
const rib4_t & get () const
Get the RIB.
Detailed Description
The BgpRib4 (IPv4 BGP Routing Information Base) class.
Examples:
route-event-bus.cc, and route-server.cc.
Definition at line 91 of file bgp-rib4.h.
Constructor & Destructor Documentation
BgpRib4()
libbgp::BgpRib4::BgpRib4 (BgpLogHandler * logger)
Construct a new BgpRib4 object with logging.
Parameters
logger Log handler to use.
Definition at line 55 of file bgp-rib4.cc.
References libbgp::BgpRibEntry< T >::ibgp_peer_asn, libbgp::BgpRib4Entry::route, libbgp::BgpRibEntry< T >::src, libbgp::BgpRibEntry< BgpRib4Entry >::src, libbgp::BgpRibEntry< BgpRib4Entry >::src_router_id, libbgp::BgpRibEntry< BgpRib4Entry >::update_id, libbgp::BgpRibEntry< T >::update_id, libbgp::BgpRibEntry< T >::weight, and libbgp::BgpRibEntry< BgpRib4Entry >::weight.
Member Function Documentation
discard()
std::vector< Prefix4 > libbgp::BgpRib4::discard (uint32_t src_router_id)
Drop all routes from RIB that originated from a BGP speaker.
Parameters
src_router_id src_router_id Originating BGP speaker's ID in network bytes order.
Returns
std::vector<Prefix4> Dropped routes.
Definition at line 380 of file bgp-rib4.cc.
get()
const rib4_t & libbgp::BgpRib4::get () const
Get the RIB.
Returns
const rib4_t& The RIB.
Definition at line 451 of file bgp-rib4.cc.
insert() [1/6]
const BgpRib4Entry * libbgp::BgpRib4::insert (BgpLogHandler * logger, const Prefix4 & route, uint32_t nexthop, int32_t weight = 0)
Insert a local route into RIB.
Local routes are routes inserted to the RIB by user. The scope (src_router_id) of local routes are 0. This method will create necessary path attribues before inserting entry to RIB (AS_PATH, ORIGIN, NEXT_HOP).
The logger pointer passed in is for attribues. (so if a attribute failed to deserialize, it will print to the provided logger).
To remove an entry inserted with this method, use 0 as src_router_id.
Parameters
logger Pointer to logger for the created path attributes to use.
route Prefix4.
nexthop Nexthop for the route.
weight weight of this entry.
Return values
NULL failed to insert.
!=NULL Inserted route.
Examples:
route-event-bus.cc, and route-filter.cc.
Definition at line 121 of file bgp-rib4.cc.
References libbgp::BgpRibEntry< BgpRib4Entry >::attribs, and libbgp::BgpPathAttribNexthop::next_hop.
insert() [2/6]
const BgpRib4Entry * libbgp::BgpRib4::insert (BgpLogHandler * logger, const Prefix4 & route, uint32_t nexthop, RouteEventBus * rev_bus, int32_t weight = 0)
Insert a local route into RIB.
Same as the other local insert, but this one notify the rev_bus after inserting route.
Parameters
logger Pointer to logger for the created path attributes to use.
route Prefix4.
nexthop Nexthop for the route.
rev_bus event bus to publish to add event.
weight weight of this entry.
Return values
NULL failed to insert.
!=NULL Inserted route.
Definition at line 176 of file bgp-rib4.cc.
References libbgp::Route4AddEvent::attribs, libbgp::BgpRibEntry< T >::attribs, libbgp::RouteEventBus::publish(), libbgp::BgpRib4Entry::route, and libbgp::Route4AddEvent::routes.
insert() [3/6]
const std::vector< BgpRib4Entry > libbgp::BgpRib4::insert (BgpLogHandler * logger, const std::vector< Prefix4 > & routes, uint32_t nexthop, int32_t weight = 0)
Insert local routes into RIB.
ame as the other local insert, but this one insert mutiple routes.
Parameters
logger Pointer to logger for the created path attributes to use.
routes Routes.
nexthop Nexthop for the route.
weight weight of this entry.
Returns
const std::vector<const BgpRib4Entry*> Inserted routes.
Definition at line 200 of file bgp-rib4.cc.
References libbgp::BgpRibEntry< BgpRib4Entry >::attribs, and libbgp::BgpPathAttribNexthop::next_hop.
insert() [4/6]
const std::vector< BgpRib4Entry > libbgp::BgpRib4::insert (BgpLogHandler * logger, const std::vector< Prefix4 > & routes, uint32_t nexthop, RouteEventBus * rev_bus, int32_t weight = 0)
Insert local routes into RIB.
ame as the other local insert, but this one insert mutiple routes and notify the route event bus.
Parameters
logger Pointer to logger for the created path attributes to use.
routes Routes.
nexthop Nexthop for the route.
rev_bus event bus to publish to add event.
weight weight of this entry.
Returns
const std::vector<const BgpRib4Entry*> Inserted routes.
Definition at line 242 of file bgp-rib4.cc.
References libbgp::Route4AddEvent::attribs, libbgp::BgpRibEntry< BgpRib4Entry >::attribs, libbgp::RouteEventBus::publish(), and libbgp::Route4AddEvent::routes.
insert() [5/6]
bool libbgp::BgpRib4::insert (uint32_t src_router_id, const Prefix4 & route, const std::vector< std::shared_ptr< BgpPathAttrib >> & attrib, int32_t weight, uint32_t ibgp_asn)
Insert a new entry into RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
route Prefix4.
attrib Path attribute.
weight weight of this entry.
ibgp_asn ASN of the peer if the route is from an IBGP peer. 0 if not.
Returns
true Prefix4 inserted/replaced.
false Prefix4 already exist and the existing one has lower metric.
Definition at line 271 of file bgp-rib4.cc.
References libbgp::BgpRibEntry< BgpRib4Entry >::update_id.
insert() [6/6]
ssize_t libbgp::BgpRib4::insert (uint32_t src_router_id, const std::vector< Prefix4 > & routes, const std::vector< std::shared_ptr< BgpPathAttrib >> & attrib, int32_t weight, uint32_t ibgp_asn)
Insert new entries into RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
routes List of routes.
attrib Path attribute.
weight weight of this entry.
ibgp_asn ASN of the peer if the route is from an IBGP peer. 0 if not.
Returns
ssize_t Number of routes inserted.
Return values
-1 Failed to insert routes.
>=0 Number of routes inserted.
Definition at line 289 of file bgp-rib4.cc.
References libbgp::BgpRibEntry< BgpRib4Entry >::update_id.
lookup() [1/2]
const BgpRib4Entry * libbgp::BgpRib4::lookup (uint32_t dest) const
Lookup a destination in RIB.
Parameters
dest The destination address in network byte order.
Returns
const BgpRib4Entry* Matching entry.
Return values
NULL no match found.
BgpRib4Entry* Matching entry.
Definition at line 409 of file bgp-rib4.cc.
References libbgp::Prefix4::includes().
lookup() [2/2]
const BgpRib4Entry * libbgp::BgpRib4::lookup (uint32_t src_router_id, uint32_t dest) const
Scoped RIB lookup.
Simular to lookup with only one argument but only lookup in routes from the given BGP speaker.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
dest The destination address in network byte order.
Returns
const BgpRib4Entry* Matching entry.
Return values
NULL no match found.
BgpRib4Entry* Matching entry.
Definition at line 433 of file bgp-rib4.cc.
References libbgp::Prefix4::includes().
withdraw() [1/4]
bool libbgp::BgpRib4::withdraw (uint32_t src_router_id, const Prefix4 & route)
Withdraw a route from RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
route Prefix4.
Returns
true Prefix4 dropped.
false Prefix4 not dropped. Likely becuase such route does not exist.
Examples:
route-event-bus.cc.
Definition at line 306 of file bgp-rib4.cc.
withdraw() [2/4]
bool libbgp::BgpRib4::withdraw (uint32_t src_router_id, const Prefix4 & route, RouteEventBus * rev_bus)
Withdrawn a route from RIB and send event to event bus.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
route Prefix4.
rev_bus Event bus to send the drop event
Returns
true Prefix4 dropped.
false Prefix4 not dropped. Likely becuase such route does not exist.
Definition at line 333 of file bgp-rib4.cc.
References libbgp::RouteEventBus::publish(), and libbgp::Route4WithdrawEvent::routes.
withdraw() [3/4]
ssize_t libbgp::BgpRib4::withdraw (uint32_t src_router_id, const std::vector< Prefix4 > & routes)
Withdraw routes from RIB.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
routes Routes.
Returns
ssize_t Number of routes dropped.
Return values
-1 Failed to drop routes.
>=0 Number of routes dropped.
Definition at line 349 of file bgp-rib4.cc.
withdraw() [4/4]
ssize_t libbgp::BgpRib4::withdraw (uint32_t src_router_id, const std::vector< Prefix4 > & routes, RouteEventBus * rev_bus)
Withdraw routes from RIB and send event to event bus.
Parameters
src_router_id Originating BGP speaker's ID in network bytes order.
routes Routes.
rev_bus Event bus to send the drop event
Returns
ssize_t Number of routes dropped.
Return values
-1 Failed to drop routes.
>=0 Number of routes dropped.
Definition at line 367 of file bgp-rib4.cc.
References libbgp::RouteEventBus::publish(), and libbgp::Route4WithdrawEvent::routes.
The documentation for this class was generated from the following files:
src/bgp-rib4.h
src/bgp-rib4.cc