libbgp: libbgp::Route Class Reference
libbgp::Route Class Reference
Route/Prefix related utilities.
#include <route.h>
Public Member Functions
Route (uint32_t prefix, uint8_t length)
Construct a new Route:: Route object.
Route (const char *prefix, uint8_t length)
Construct a new Route:: Route object.
bool includes (uint32_t address) const
Test if an address is inside this prefix.
bool includes (const char *address) const
Test if an address is inside this prefix.
bool includes (const Route &other) const
Test if another prefix is inside this prefix.
bool includes (uint32_t prefix, uint8_t length) const
Test if another prefix is inside this prefix.
bool includes (const char *prefix, uint8_t length) const
Test if another prefix is inside this prefix.
bool operator== (const Route &other) const
Test if two routes are equals.
bool operator> (const Route &other) const
bool operator< (const Route &other) const
bool operator>= (const Route &other) const
bool operator<= (const Route &other) const
bool operator!= (const Route &other) const
bool set (uint32_t prefix, uint8_t length)
bool setPrefix (uint32_t prefix)
Set prefix.
bool setLength (uint8_t length)
Set netmask.
uint32_t getPrefix () const
Get prefix.
uint8_t getLength () const
Get netmask.
uint32_t getMask () const
Get netmask.
Static Public Member Functions
static bool Includes (uint32_t prefix, uint8_t length, uint32_t address)
Test if an address is inside a prefix.
static bool Includes (uint32_t prefix_a, uint8_t length_a, uint32_t prefix_b, uint8_t length_b)
Test if a prefix is inside another prefix.
Detailed Description
Route/Prefix related utilities.
Examples:
route-event-bus.cc, and route-filter.cc.
Definition at line 23 of file route.h.
Constructor & Destructor Documentation
Route() [1/2]
libbgp::Route::Route (uint32_t prefix, uint8_t length)
Construct a new Route:: Route object.
Parameters
prefix Prefix in network bytes order.
length Netmask in CIDR notation.
Exceptions
bad_route_length Netmask invalid.
Definition at line 44 of file route.cc.
Route() [2/2]
libbgp::Route::Route (const char * prefix, uint8_t length)
Construct a new Route:: Route object.
Parameters
prefix Prefix in dotted string notation.
length Netmask in CIDR notation.
Exceptions
bad_route_length Netmask invalid.
Definition at line 57 of file route.cc.
Member Function Documentation
getLength()
uint8_t libbgp::Route::getLength () const
Get netmask.
Returns
uint8_t The netmask in CIDR notation.
Definition at line 235 of file route.cc.
getMask()
uint32_t libbgp::Route::getMask () const
Get netmask.
Returns
uint32_t The netmask in network byte order.
Exceptions
bad_route_length Netmask invalid.
Definition at line 245 of file route.cc.
getPrefix()
uint32_t libbgp::Route::getPrefix () const
Get prefix.
Returns
uint32_t The prefix in network byte order.
Definition at line 226 of file route.cc.
Includes() [1/2]
bool libbgp::Route::Includes (uint32_t prefix, uint8_t length, uint32_t address) static
Test if an address is inside a prefix.
Parameters
prefix The prefix in network bytes order..
length The netmask of prefix in CIDR notation.
address The address in network bytes order.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 72 of file route.cc.
Includes() [2/2]
bool libbgp::Route::Includes (uint32_t prefix_a, uint8_t length_a, uint32_t prefix_b, uint8_t length_b) static
Test if a prefix is inside another prefix.
Parameters
prefix_a The prefix in network bytes order..
length_a The netmask of prefix in CIDR notation.
prefix_b The prefix to test against.
length_b The netmask of prefix to test against in CIDR notation.
Returns
true prefix_b is in prefix_a.
false prefix_b is not in prefix_a.
Definition at line 87 of file route.cc.
includes() [1/5]
bool libbgp::Route::includes (uint32_t address) const
Test if an address is inside this prefix.
Parameters
address The address in network bytes order.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 100 of file route.cc.
Referenced by libbgp::BgpFilterRule::apply(), includes(), and libbgp::BgpRib::lookup().
includes() [2/5]
bool libbgp::Route::includes (const char * address) const
Test if an address is inside this prefix.
Parameters
address The address in dotted string notation.
Returns
true The address is in the prefix.
false The address in not in the prefix.
Definition at line 111 of file route.cc.
References includes().
includes() [3/5]
bool libbgp::Route::includes (const Route & other) const
Test if another prefix is inside this prefix.
Parameters
other The other prefix.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 138 of file route.cc.
References includes().
includes() [4/5]
bool libbgp::Route::includes (uint32_t prefix, uint8_t length) const
Test if another prefix is inside this prefix.
Parameters
prefix The prefix in network bytes order.
length The netmask of prefix in CIDR notation.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 125 of file route.cc.
includes() [5/5]
bool libbgp::Route::includes (const char * prefix, uint8_t length) const
Test if another prefix is inside this prefix.
Parameters
prefix The prefix in dotted string notation.
length The netmask of prefix in CIDR notation.
Returns
true The other prefix is in this prefix.
false The other prefix is not in this prefix.
Definition at line 150 of file route.cc.
References includes().
operator==()
bool libbgp::Route::operator== (const Route & other) const
Test if two routes are equals.
Parameters
other The other route object.
Returns
true The routes are equal.
false The routes are different.
Definition at line 163 of file route.cc.
setLength()
bool libbgp::Route::setLength (uint8_t length)
Set netmask.
Parameters
length The netmask in CIDR notation.
Returns
true Netmask set.
false Failed to set netmask.
Definition at line 215 of file route.cc.
setPrefix()
bool libbgp::Route::setPrefix (uint32_t prefix)
Set prefix.
Parameters
prefix The prefix to set in network byte order.
Returns
true Prefix set.
false Failed to set prefix.
Definition at line 203 of file route.cc.
The documentation for this class was generated from the following files:
src/route.h
src/route.cc