libbgp: libbgp::BgpLogHandler Class Reference
libbgp::BgpLogHandler Class Reference
The BgpLogHandler class.
#include <bgp-log-handler.h>
Public Member Functions
void stdout (const char *format_str,...)
Print message to stdout.
void stderr (const char *format_str,...)
Print message to stderr.
virtual ~BgpLogHandler ()
Destroy the Bgp Log Handler object.
Protected Member Functions
virtual void stdoutImpl (const char *str)
stdout implementation, by default it writes to the real stdout. You may choose to override the implementation.
virtual void stderrImpl (const char *str)
stderr implementation, by default it writes to the real stderr. You may choose to override the implementation.
Detailed Description
The BgpLogHandler class.
The log handler class is used by various other classes to print message.
Definition at line 23 of file bgp-log-handler.h.
Member Function Documentation
stderr()
void libbgp::BgpLogHandler::stderr (const char * format_str, ...)
Print message to stderr.
Parameters
format_str printf format string.
... variables.
Definition at line 40 of file bgp-log-handler.cc.
References stderrImpl().
Referenced by stderrImpl(), libbgp::BgpOpenMessage::write(), libbgp::BgpCapability4BytesAsn::write(), libbgp::BgpCapabilityUnknow::write(), libbgp::BgpUpdateMessage::write(), libbgp::BgpPathAttribOrigin::write(), libbgp::BgpPathAttribAsPath::write(), libbgp::BgpPathAttribNexthop::write(), libbgp::BgpPathAttribMed::write(), libbgp::BgpPathAttribLocalPref::write(), libbgp::BgpPathAttribAtomicAggregate::write(), libbgp::BgpPathAttribAggregator::write(), libbgp::BgpPathAttribAs4Path::write(), libbgp::BgpPathAttribAs4Aggregator::write(), and libbgp::BgpPathAttribCommunity::write().
stderrImpl()
void libbgp::BgpLogHandler::stderrImpl (const char * str) protected virtual
stderr implementation, by default it writes to the real stderr. You may choose to override the implementation.
Parameters
str
Definition at line 55 of file bgp-log-handler.cc.
References stderr().
Referenced by stderr(), and ~BgpLogHandler().
stdout()
void libbgp::BgpLogHandler::stdout (const char * format_str, ...)
Print message to stdout.
Parameters
format_str printf format string.
... variables.
Definition at line 23 of file bgp-log-handler.cc.
References stdoutImpl().
Referenced by stdoutImpl().
stdoutImpl()
void libbgp::BgpLogHandler::stdoutImpl (const char * str) protected virtual
stdout implementation, by default it writes to the real stdout. You may choose to override the implementation.
Parameters
str
Definition at line 51 of file bgp-log-handler.cc.
References stdout().
Referenced by stdout(), and ~BgpLogHandler().
The documentation for this class was generated from the following files:
src/bgp-log-handler.h
src/bgp-log-handler.cc