libbgp: libbgp::BgpPathAttribMpReachNlriUnknow Class Reference
libbgp::BgpPathAttribMpReachNlriUnknow Class Reference
MP-BGP ReachNlri container for unknow AFI/SAFI.
#include <bgp-path-attrib.h>
Public Member Functions
BgpPathAttribMpReachNlriUnknow (BgpLogHandler *logger)
BgpPathAttribMpReachNlriUnknow (BgpLogHandler *logger, const uint8_t *nexthop, size_t nexthop_len, const uint8_t *nlri, size_t nlri_len)
BgpPathAttrib * clone () const
Clone the attribute.
ssize_t parse (const uint8_t *buffer, size_t length)
Deserialize a BGP update message path attribute.
ssize_t write (uint8_t *buffer, size_t buffer_sz) const
Serialize a BGP update message path attribute.
ssize_t doPrint (size_t indent, uint8_t **to, size_t *buf_sz) const
Print implementation.
ssize_t length () const
Get size in bytes required to serialize the object.
const uint8_t * getNexthop () const
const uint8_t * getNlri () const
size_t getNexthopLength () const
size_t getNlriLength () const
def __init__ (self, args)
def clone (self)
def parse (self, buffer, length)
def write (self, buffer, buffer_sz)
def doPrint (self, indent, to, buf_sz)
def length (self)
def getNexthop (self)
def getNlri (self)
def getNexthopLength (self)
def getNlriLength (self)
Public Member Functions inherited from libbgp::BgpPathAttribMpNlriBase
BgpPathAttribMpNlriBase (BgpLogHandler *logger)
def __init__ (self, logger)
Public Member Functions inherited from libbgp::BgpPathAttrib
BgpPathAttrib (BgpLogHandler *logger)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
BgpPathAttrib (BgpLogHandler *logger, const uint8_t *value, uint16_t val_len)
Construct a new Bgp Path Attrib:: Bgp Path Attrib object.
BgpPathAttrib * clone (BgpLogHandler *new_logger) const
Clone the attribute and replace logger.
virtual ~BgpPathAttrib ()
Destroy the Bgp Path Attrib:: Bgp Path Attrib object.
def __init__ (self, args)
def doPrint (self, indent, to, buf_sz)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def clone (self, args)
Public Member Functions inherited from libbgp.Serializable
def __init__ (self, args, kwargs)
def parse (self, arg2, msg_sz)
def write (self, to, buf_sz)
def length (self)
def hasError (self)
def getErrorCode (self)
def getErrorSubCode (self)
def getError (self)
def getErrorLength (self)
def setLogger (self, logger)
Serializable (BgpLogHandler *logger)
Construct a new Serializable:: Serializable object.
~Serializable ()
Destroy the Serializable:: Serializable object.
ssize_t print (uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string.
ssize_t print (size_t indent, uint8_t *to, size_t buf_sz) const
Print the Serializable object as human readable string, with indentation.
bool hasError () const
Check if error information available.
uint8_t getErrorCode () const
uint8_t getErrorSubCode () const
const uint8_t * getError () const
size_t getErrorLength () const
void setLogger (BgpLogHandler *logger)
Replace logger for this object.
Public Attributes
this
Public Attributes inherited from libbgp::BgpPathAttribMpNlriBase
uint16_t afi
Address Family Identifier.
uint8_t safi
Subsequent Address Family Identifier.
this
Public Attributes inherited from libbgp::BgpPathAttrib
bool optional
Attribute flag: Optional.
bool transitive
Attribute flag: Transitive.
bool partial
Attribute flag: partial.
bool extended
Attribute flag: extended.
uint8_t type_code
Attribute type code.
this
Additional Inherited Members
Static Public Member Functions inherited from libbgp::BgpPathAttribMpNlriBase
static int16_t GetAfiFromBuffer (const uint8_t *buffer, size_t length)
Static Public Member Functions inherited from libbgp::BgpPathAttrib
static uint8_t GetTypeFromBuffer (const uint8_t *buffer, size_t buffer_sz)
Static Public Attributes inherited from libbgp::BgpPathAttribMpNlriBase
GetAfiFromBuffer = staticmethod(_libbgp.BgpPathAttribMpNlriBase_GetAfiFromBuffer)
afi = _swig_property(_libbgp.BgpPathAttribMpNlriBase_afi_get, _libbgp.BgpPathAttribMpNlriBase_afi_set)
safi = _swig_property(_libbgp.BgpPathAttribMpNlriBase_safi_get, _libbgp.BgpPathAttribMpNlriBase_safi_set)
Static Public Attributes inherited from libbgp::BgpPathAttrib
optional = _swig_property(_libbgp.BgpPathAttrib_optional_get, _libbgp.BgpPathAttrib_optional_set)
transitive = _swig_property(_libbgp.BgpPathAttrib_transitive_get, _libbgp.BgpPathAttrib_transitive_set)
partial = _swig_property(_libbgp.BgpPathAttrib_partial_get, _libbgp.BgpPathAttrib_partial_set)
extended = _swig_property(_libbgp.BgpPathAttrib_extended_get, _libbgp.BgpPathAttrib_extended_set)
type_code = _swig_property(_libbgp.BgpPathAttrib_type_code_get, _libbgp.BgpPathAttrib_type_code_set)
GetTypeFromBuffer = staticmethod(_libbgp.BgpPathAttrib_GetTypeFromBuffer)
Get type of attribute from buffer.
Protected Member Functions inherited from libbgp::BgpPathAttribMpNlriBase
ssize_t parseHeader (const uint8_t *buffer, size_t length)
Protected Member Functions inherited from libbgp::BgpPathAttrib
ssize_t parseHeader (const uint8_t *buffer, size_t length)
Utility function to parse attribute header. (Flag, type, length)
ssize_t printFlags (size_t indent, uint8_t **to, size_t *buf_sz) const
Utility function to print flags for attribute.
ssize_t writeHeader (uint8_t *buffer, size_t buffer_sz) const
Write attribute header to buffer. (Flag, Type)
Protected Member Functions inherited from libbgp.Serializable
void setError (uint8_t err, uint8_t suberr, const uint8_t *data, size_t data_len)
Set the error information.
void forwardParseError (const Serializable &other)
Forward error information from other Serializable object.
Static Protected Member Functions inherited from libbgp.Serializable
static ssize_t _print (size_t indent, uint8_t **to, size_t *buf_left, const char *format,...)
Print helper.
Protected Attributes inherited from libbgp::BgpPathAttrib
uint16_t value_len
Attribute length. Length field is only used in deserialization for parseHeader() to pass length field in header to the underlying deserializers. The length field is ignored when serialize.
Protected Attributes inherited from libbgp.Serializable
uint8_t err_code
uint8_t err_subcode
size_t err_len
uint8_t * err_data
BgpLogHandler * logger
Detailed Description
MP-BGP ReachNlri container for unknow AFI/SAFI.
Definition at line 493 of file bgp-path-attrib.h.
Member Function Documentation
clone()
BgpPathAttrib * libbgp::BgpPathAttribMpReachNlriUnknow::clone () const virtual
Clone the attribute.
Returns
BgpPathAttrib* Pointer to the cloned attribute.
Exceptions
has_error There's error in the attribute and the attribute can not be clone.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 1726 of file bgp-path-attrib.cc.
References libbgp.Serializable::hasError(), and libbgp::BgpLogHandler::log().
doPrint()
ssize_t libbgp::BgpPathAttribMpReachNlriUnknow::doPrint (size_t indent, uint8_t ** to, size_t * buf_sz) const virtual
Print implementation.
Parameters
indent indent level.
to The pointer to the pointer to the string buffer.
buf_sz The pointer to the counter of avaliable buffer space.
Returns
ssize_t ssize_t Bytes written.
Return values
-1 Failed to print.
>= 0 Bytes written.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 1802 of file bgp-path-attrib.cc.
References libbgp.Serializable::_print(), and libbgp::BgpPathAttrib::printFlags().
length()
ssize_t libbgp::BgpPathAttribMpReachNlriUnknow::length () const virtual
Get size in bytes required to serialize the object.
Returns
ssize_t Size in btyes.
Return values
-1 Failed to get size.
>=0 Size in btyes.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 1814 of file bgp-path-attrib.cc.
parse()
ssize_t libbgp::BgpPathAttribMpReachNlriUnknow::parse (const uint8_t * from, size_t msg_sz) virtual
Deserialize a BGP update message path attribute.
Parameters
from Pointer to message body buffer.
msg_sz Size of message.
Returns
ssize_t Bytes read.
Return values
-1 Deserialization error. Error may be logged.
>=0 Bytes read.
Exceptions
bad_parse Internal deserialization error.
bad_type The type of message/field member in buffer does not match the attribute type of container.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 1736 of file bgp-path-attrib.cc.
References libbgp::BgpLogHandler::log(), and libbgp::BgpPathAttrib::parseHeader().
write()
ssize_t libbgp::BgpPathAttribMpReachNlriUnknow::write (uint8_t * to, size_t buf_sz) const virtual
Serialize a BGP update message path attribute.
Parameters
to Pointer to destination buffer.
buf_sz Max write size.
Returns
ssize_t Bytes written.
Return values
-1 Serialization error. Error may be logged.
>=0 Bytes written.
Reimplemented from libbgp::BgpPathAttrib.
Definition at line 1774 of file bgp-path-attrib.cc.
References libbgp::BgpLogHandler::log().
The documentation for this class was generated from the following files:
src/bgp-path-attrib.h
src/libbgp.py
src/bgp-path-attrib.cc